// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jejvkaewycrtpbgyxjzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplanZrYWV3eWNydHBiZ3l4anpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDg4ODEsImV4cCI6MjA2NzYyNDg4MX0.worn3uXciQQPZMDXX29DJUMBfACPoSa5CLtnHCg2X8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});